apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: k29v8r7rl-nodejs 
  janus-idp.io/tekton: k29v8r7rl-nodejs
  backstage.io/kubernetes-id: k29v8r7rl-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: k29v8r7rl-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  