apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: k29v8r7rl-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: k29v8r7rl-nodejs 
  name: k29v8r7rl-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: k29v8r7rl-nodejs 
